In [19]:
import pandas as pd
import numpy as np

John's pandas Notes

In [20]:
a = np.array(['NP3', 'AA-PURE'])
a

array(['NP3', 'AA-PURE'], dtype='<U7')

In [21]:
b = np.array([410])
b

array([410])

In [22]:
c = np.array([0.71, 0.88])
c

array([0.71, 0.88])

In [23]:
bc = np.multiply(b, c)
bc

array([291.1, 360.8])

In [24]:
d = np.array([b, c, bc])
d

/var/folders/81/hphqs12d1t59l2tc7hrc297r0000gn/T/ipykernel_10828/3189495442.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.array([b, c, bc])


array([array([410]), array([0.71, 0.88]), array([291.1, 360.8])],
      dtype=object)